name: 'trigger umami'

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Run Umami' # 触发 umami api
        run: curl https://umami.sponge.eu.org/api/websites -H 'Accept: application/json' -H 'Authorization: Bearer 05VJs2P+hrCUk6cLA8PoSsDKXVdsIPXVD1PZHiTaOTncOB6PgztmO1ztZ0bgFhYLFdZdo0ENNIEWNIx5PLPD8qYxqo5qOkPT2lTuGmCx5OgNCOg/NS5yBk6MtBtSSLQ2zC1jtHHPNr3OXerjJtXsOGE2L296Oj+CRGO/zpCHT5L/+Mfp0nm88Q5O0NQenVVGNlR6qRblPJl6CzHbXB+ZSWLdDA+zQWqxjdoPdIKSHW6tTo3AivWWI8ULI6sU0EO5MWaFIfZJk69vzGv5QEUl09ZxEXq8gB/6VjGFz+Ox4o7IRXRr6fBkkoWmF4upQDYDquuApg3BVTggVyLW01+59OIv6WNjq8hxxg=='
